---
driver:
  name: vagrant
  config:
    require_chef_omnibus: true
  network:
    - ["forwarded_port", { guest: 8983, host: 8983 }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[solr-jetty::default]
    attributes:
