---
driver:
  name: vagrant
  config:
    require_chef_omnibus: true
  network:
    - ["forwarded_port", { guest: 8983, host: 8983 }]

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: kitchen

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[solr-jetty::default]
    attributes:
