name             'solr-jetty'
maintainer       'E Camden Fisher'
maintainer_email 'camden@northpage.com'
license          'Apache 2.0'
description      'Installs/Configures solr-jetty'
long_description 'Installs/Configures solr-jetty'
version          '0.2.2'

depends 'libarchive', '~> 0.6'
depends 'java', '~> 1.0'
depends 'iptables', '~> 0.14.0'
